### PR TITLE
terrateam testing

### PR DESCRIPTION
**Pull request by pranavs1995**

### CODE REVIEW

**Comment by pranavs1995** [comment]
terratest plan

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam apply

**Comment by pranavs1995** [comment]
terrateam apply

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranav-shankar-swi** [comment]
terrateam plan

**Comment by pranav-shankar-swi** [comment]
terrateam unlock

**Comment by pranavs1995** [comment]
terrateam unlock

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam unlock

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam plan

**Comment by pranav-shankar-swi** [comment]
terrateam plan

**Comment by pranav-shankar-swi** [comment]
terrateam plan

**Comment by pranavs1995** [comment]
terrateam apply

**Comment by pranav-shankar-swi** [comment]
terrateam plan

**Comment by pranav-shankar-swi** [comment]
terrateam apply

**Comment by pranav-shankar-swi** [comment]
terrateam plan dir:deploy/dev/eu-west-1/infrastructure/

**Pull request merged**
